/* ═══════════════════════════════════════════════════════
   Editor — MOGADOCLab Quantum Structure Studio
   ═══════════════════════════════════════════════════════ */

// EDITOR
// ═══════════════════════════════════════════════════════════

const EDITOR_DRAFT_KEY='mogadoclab_editor_draft_v2';
const APP_STATE_KEY='mogadoclab_state_v3';
const editorState={history:[],future:[],lastValue:'',dirty:false,lastParsedHash:'',isApplying:false};

function formatXYZFromMol(mol){
  let out=`${mol.atoms.length}\n${mol.name||'Molecule'}\n`;
  mol.atoms.forEach(a=>{out+=`${a.symbol.padEnd(4)} ${a.x.toFixed(6).padStart(12)} ${a.y.toFixed(6).padStart(12)} ${a.z.toFixed(6).padStart(12)}\n`;});
  return out;
}
function formatJSONFromMol(mol){
  return JSON.stringify({
    name: mol.name||'Molecule',
    atoms: mol.atoms.map(a=>({symbol:a.symbol,x:+a.x.toFixed(6),y:+a.y.toFixed(6),z:+a.z.toFixed(6)})),
    bonds: mol.bonds.map(b=>({a:b.a,b:b.b,order:b.order??1,type:b.type||'covalent'}))
  },null,2);
}
function formatMOLFromMol(mol){
  const name=(mol.name||'Molecule').slice(0,80);
  const nA=Math.min(mol.atoms.length,999), nB=Math.min(mol.bonds.length,999);
  let out=`${name}\nMOGADOCLab\nGenerated by PI-grade editor\n${String(nA).padStart(3,' ')}${String(nB).padStart(3,' ')}  0  0  0  0            999 V2000\n`;
  mol.atoms.slice(0,999).forEach(a=>{
    out+=`${a.x.toFixed(4).padStart(10)}${a.y.toFixed(4).padStart(10)}${a.z.toFixed(4).padStart(10)} ${a.symbol.padEnd(3)} 0  0  0  0  0  0  0  0  0  0  0  0\n`;
  });
  mol.bonds.slice(0,999).forEach(b=>{
    const order=(b.order===1.5?4:Math.max(1,Math.min(3,Math.round(b.order||1))));
    out+=`${String((b.a||0)+1).padStart(3,' ')}${String((b.b||0)+1).padStart(3,' ')}${String(order).padStart(3,' ')}  0  0  0  0\n`;
  });
  out+='M  END\n';
  return out;
}
function formatMolTo(fmt,mol){
  if(fmt==='json') return formatJSONFromMol(mol);
  if(fmt==='mol') return formatMOLFromMol(mol);
  if(fmt==='pdb') return formatXYZFromMol(mol);
  return formatXYZFromMol(mol);
}
function getEditorEl(){ return document.getElementById('rawEditor'); }
function getEditorFormat(){ return document.getElementById('editorFormat').value; }
function editorHash(txt){ return `${txt.length}:${txt.slice(0,120)}`; }
function editorSetValue(text,{pushHistory=false,markDirty=true}={}){
  const el=getEditorEl();
  if(pushHistory && !editorState.isApplying && el.value!==text){
    editorState.history.push(el.value);
    if(editorState.history.length>100) editorState.history.shift();
    editorState.future.length=0;
  }
  editorState.isApplying=true;
  el.value=text;
  editorState.isApplying=false;
  editorState.lastValue=text;
  if(markDirty!==null) editorState.dirty=!!markDirty;
  refreshEditorMeta();
  saveEditorDraft();
}
function refreshEditorMeta(extra={}){
  const el=getEditorEl(), val=el.value||'', lines=val?val.split('\n').length:0;
  document.getElementById('editorFmtChip').textContent=getEditorFormat().toUpperCase();
  document.getElementById('editorLineChip').textContent=`${lines} line${lines===1?'':'s'}`;
  document.getElementById('editorCharChip').textContent=`${val.length} chars`;
  const dirty=document.getElementById('editorDirtyChip');
  dirty.textContent=editorState.dirty?'Unsaved':'Clean';
  dirty.className='editor-chip'+(editorState.dirty?' dirty':'');
  if(extra.validity){
    const vc=document.getElementById('editorValidityChip');
    vc.textContent=extra.validity.text;
    vc.className='editor-chip '+extra.validity.cls;
  }
  if(extra.counts){
    document.getElementById('editorAtomChip').textContent=`${extra.counts.atoms} atoms`;
    document.getElementById('editorBondChip').textContent=`${extra.counts.bonds} bonds`;
  }
}
function editorValidate({quiet=false}={}){
  const text=getEditorEl().value.trim(), fmt=getEditorFormat();
  if(!text){
    refreshEditorMeta({validity:{text:'Empty',cls:'bad'},counts:{atoms:0,bonds:0}});
    if(!quiet) notify('Editor is empty','error');
    return null;
  }
  try{
    const mol=parseMolecule('editor.'+fmt,text);
    refreshEditorMeta({validity:{text:'Valid',cls:'good'},counts:{atoms:mol.atoms.length,bonds:mol.bonds.length}});
    if(!quiet) notify(`Validated ${mol.atoms.length} atoms and ${mol.bonds.length} bonds`,'success');
    return mol;
  }catch(e){
    refreshEditorMeta({validity:{text:'Invalid',cls:'bad'},counts:{atoms:0,bonds:0}});
    if(!quiet) notify('Validation failed: '+e.message,'error');
    return null;
  }
}
function parseFromEditor(){
  const mol=editorValidate({quiet:true});
  if(!mol) return notify('Parse error: invalid editor content','error');
  loadMolecule('From editor',mol);
  editorState.dirty=false;
  editorState.lastParsedHash=editorHash(getEditorEl().value);
  refreshEditorMeta({validity:{text:'Rendered',cls:'good'},counts:{atoms:mol.atoms.length,bonds:mol.bonds.length}});
  saveEditorDraft();
  notify(`Rendered ${mol.atoms.length} atoms from ${getEditorFormat().toUpperCase()} editor`,'success');
}
function loadEditorFromMolecule(){
  if(!molecule)return notify('No structure loaded','error');
  const fmt=getEditorFormat();
  editorSetValue(formatMolTo(fmt,molecule),{pushHistory:true,markDirty:false});
  editorState.lastParsedHash=editorHash(getEditorEl().value);
  editorValidate({quiet:true});
  notify(`Loaded current molecule into ${fmt.toUpperCase()} editor`,'success');
}
function editorUndo(){
  if(!editorState.history.length) return notify('Nothing to undo','error');
  const el=getEditorEl();
  editorState.future.push(el.value);
  const prev=editorState.history.pop();
  editorSetValue(prev,{pushHistory:false,markDirty:true});
}
function editorRedo(){
  if(!editorState.future.length) return notify('Nothing to redo','error');
  const el=getEditorEl();
  editorState.history.push(el.value);
  const next=editorState.future.pop();
  editorSetValue(next,{pushHistory:false,markDirty:true});
}
function editorPrettify(){
  const mol=editorValidate({quiet:true});
  if(!mol) return notify('Cannot prettify invalid content','error');
  const pretty=formatMolTo(getEditorFormat(),{...mol,name:molecule?.name||'Molecule'});
  editorSetValue(pretty,{pushHistory:true,markDirty:true});
  editorValidate({quiet:true});
  notify('Editor content normalized','success');
}
function editorConvertFormat(){
  const mol=editorValidate({quiet:true}) || molecule;
  if(!mol) return notify('Nothing valid to convert','error');
  const fmt=getEditorFormat();
  editorSetValue(formatMolTo(fmt,{...mol,name:mol.name||molecule?.name||'Molecule'}),{pushHistory:true,markDirty:true});
  editorValidate({quiet:true});
  notify(`Converted editor to ${fmt.toUpperCase()}`,'success');
}
function editorCopy(){
  const val=getEditorEl().value;
  if(!val.trim()) return notify('Editor is empty','error');
  navigator.clipboard.writeText(val).then(()=>notify('Editor text copied','success')).catch(()=>notify('Clipboard copy failed','error'));
}
function editorDownload(){
  const val=getEditorEl().value;
  if(!val.trim()) return notify('Editor is empty','error');
  const fmt=getEditorFormat(), mime=fmt==='json'?'application/json':'text/plain';
  download(val,`${(molecule?.name||'molecule_editor').replace(/\s+/g,'_')}.${fmt}`,mime);
  notify(`Saved ${fmt.toUpperCase()} editor text`,'success');
}
function saveEditorDraft(){
  try{
    const payload={text:getEditorEl().value,format:getEditorFormat(),dirty:editorState.dirty,lastParsedHash:editorState.lastParsedHash};
    localStorage.setItem(EDITOR_DRAFT_KEY,JSON.stringify(payload));
  }catch(_){}
}
function restoreEditorDraft(){
  try{
    const raw=localStorage.getItem(EDITOR_DRAFT_KEY);
    if(!raw) return false;
    const draft=JSON.parse(raw);
    if(draft.format) document.getElementById('editorFormat').value=draft.format;
    if(typeof draft.text==='string' && draft.text.trim()){
      editorSetValue(draft.text,{pushHistory:false,markDirty:!!draft.dirty});
      editorState.lastParsedHash=draft.lastParsedHash||'';
      editorValidate({quiet:true});
      return true;
    }
  }catch(_){}
  return false;
}
function saveAppState(){
  try{
    const state={
      savedViewportWidth: window.innerWidth || 0,
      theme: document.documentElement.getAttribute('data-theme')||'dark',
      viewMode, lightingMode, colorScheme, rotMode, rotEasing,
      rotTilt: Math.round((rotTiltAngle||0)*180/Math.PI),
      autoRotate, showLabels, showInfo,
      bg: document.getElementById('canvasArea').getAttribute('data-bg')||'grid',
      atomScale: document.getElementById('atomScale').value,
      bondWidth: document.getElementById('bondWidth').value,
      depthFog: document.getElementById('depthFog').value,
      glowAmt: document.getElementById('glowAmt').value,
      rotSpeed: document.getElementById('rotSpeed').value,
      molecule: molecule?{
        name:molecule.name||'Molecule',
        atoms:molecule.atoms.map(a=>({symbol:a.symbol,x:a.x,y:a.y,z:a.z,idx:a.idx})),
        bonds:molecule.bonds.map(b=>({a:b.a,b:b.b,order:b.order,type:b.type}))
      }:null
    };
    localStorage.setItem(APP_STATE_KEY,JSON.stringify(state));
  }catch(_){}
}
function restoreAppState(){
  try{
    const raw=localStorage.getItem(APP_STATE_KEY);
    if(!raw) return false;
    const s=JSON.parse(raw);
    const isCompactViewport = window.matchMedia('(max-width: 768px)').matches;
    const wasSavedFromCompactViewport = Number(s.savedViewportWidth||0) > 0 && Number(s.savedViewportWidth) <= 768;
    if(s.theme) setTheme(s.theme==='dark'?'dark':s.theme);
    if(s.bg) setBg(s.bg);
    if(s.viewMode) setViewMode(s.viewMode);
    if(s.lightingMode) setLighting(s.lightingMode);
    if(s.colorScheme) setColorScheme(s.colorScheme);
    if(s.rotMode) setRotMode(s.rotMode);
    if(typeof s.rotEasing==='boolean') setRotEasing(s.rotEasing);
    if(typeof s.rotTilt==='number') { document.getElementById('rotTilt').value=s.rotTilt; setRotTilt(s.rotTilt); }
    [['atomScale',s.atomScale],['bondWidth',s.bondWidth],['depthFog',s.depthFog],['glowAmt',s.glowAmt],['rotSpeed',s.rotSpeed]].forEach(([id,v])=>{ if(v!=null) document.getElementById(id).value=v; });
    updateDisplay();
    const sidebar=document.getElementById('sidebar');
    sidebar.classList.remove('collapsed','expanded','super-expanded');
    document.getElementById('searchSection')?.classList.remove('search-expanded');
    if(isCompactViewport){
      sidebar.classList.remove('expanded','super-expanded');
      sidebar.classList.add('collapsed');
      document.getElementById('searchSection')?.classList.remove('search-expanded');
    } else if(wasSavedFromCompactViewport){
      sidebar.classList.remove('collapsed');
      document.getElementById('searchSection')?.classList.remove('search-expanded');
    }
    normalizeSidebarState?.({forceDesktopVisible:true});
    const dbExpandBtn=document.getElementById('dbExpandBtn');
    if(dbExpandBtn){
      if(document.getElementById('searchSection')?.classList.contains('search-expanded')) dbExpandBtn.textContent='⤡ Compact';
      else dbExpandBtn.textContent='⤢ Expand';
    }
    document.getElementById('sidebarToggle').textContent=document.getElementById('sidebar').classList.contains('collapsed')?'›':'‹';
    document.getElementById('editorPanel').classList.add('hidden');
    updateSidebarToggleUI();
    if(s.molecule?.atoms?.length) loadMolecule(s.molecule.name||'Recovered Molecule',{atoms:s.molecule.atoms,bonds:s.molecule.bonds||[]});
    if(s.autoRotate && !autoRotate) toggleAutoRotate();
    if(s.showLabels && !showLabels) toggleLabels();
    if(s.showInfo && !showInfo) toggleInfo();
    return true;
  }catch(_){
    return false;
  }
}
try{
  localStorage.removeItem('mogadoclab_state_v2');
}catch(_){}
function initEditorRegime(){
  const ed=getEditorEl(), fmt=document.getElementById('editorFormat');
  ed.addEventListener('input',()=>{
    if(editorState.isApplying) return;
    if(ed.value!==editorState.lastValue){
      editorState.history.push(editorState.lastValue);
      if(editorState.history.length>100) editorState.history.shift();
      editorState.future.length=0;
      editorState.lastValue=ed.value;
    }
    editorState.dirty=editorHash(ed.value)!==editorState.lastParsedHash;
    refreshEditorMeta();
    saveEditorDraft();
  });
  ed.addEventListener('keydown',e=>{
    if((e.ctrlKey||e.metaKey)&&e.key==='Enter'){ parseFromEditor(); e.preventDefault(); }
    if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){ editorDownload(); e.preventDefault(); }
    if((e.ctrlKey||e.metaKey)&&!e.shiftKey&&e.key.toLowerCase()==='z'){ editorUndo(); e.preventDefault(); }
    if(((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='y')||((e.ctrlKey||e.metaKey)&&e.shiftKey&&e.key.toLowerCase()==='z')){ editorRedo(); e.preventDefault(); }
  });
  fmt.addEventListener('change',()=>{
    refreshEditorMeta();
    if(ed.value.trim()) editorConvertFormat();
    saveEditorDraft();
  });
  restoreEditorDraft();
  if(!ed.value.trim() && molecule) loadEditorFromMolecule();
  else refreshEditorMeta();
  window.addEventListener('beforeunload',()=>{ saveEditorDraft(); saveAppState(); });
}
// ─── DRAG & DROP ──────────────────────────────────────────
const fileDrop=document.getElementById('fileDrop');
fileDrop.addEventListener('dragover',e=>{e.preventDefault();fileDrop.classList.add('drag-over');});
fileDrop.addEventListener('dragleave',()=>fileDrop.classList.remove('drag-over'));
function handleDroppedFile(file){
  if(!file) return;
  const reader=new FileReader();
  reader.onload=ev=>{
    try{
      loadStructureText(file.name, ev.target.result, { displayName: file.name.replace(/\.[^.]+$/,'') });
    }catch(err){notify('Import failed: '+err.message,'error');}
  };
  reader.readAsText(file);
}
fileDrop.addEventListener('drop',e=>{e.preventDefault();fileDrop.classList.remove('drag-over');handleDroppedFile(e.dataTransfer.files[0]);});
const canvasArea=document.getElementById('canvasArea');
canvasArea.addEventListener('dragover',e=>e.preventDefault());
canvasArea.addEventListener('drop',e=>{e.preventDefault();handleDroppedFile(e.dataTransfer.files[0]);});

// ─── NOTIFICATIONS ─────────────────────────────────────────
let notifTimer=null;
function notify(msg,type='success'){
  const el=document.getElementById('notification'),icons={success:'✓',error:'✕',info:'ℹ'};
  document.getElementById('notifIcon').textContent=icons[type]||'';
  document.getElementById('notifMsg').textContent=msg;
  el.className='show '+type;
  if(notifTimer)clearTimeout(notifTimer);
  notifTimer=setTimeout(()=>el.className='',3500);
}
function clearMolecule(){
  if(typeof clearTrajectory==='function' && trajectoryFrames?.length){
    clearTrajectory();
  }
  molecule=null;
  document.getElementById('emptyState').style.display='flex';
  const mb=document.getElementById('moleculeName');mb.textContent='No structure loaded';mb.classList.remove('loaded');
  document.getElementById('headerFormula').textContent='';document.getElementById('headerFormula').classList.remove('visible');
  ['statAtoms','statBonds','statElems'].forEach(id=>document.getElementById(id).textContent='0');
  ['statMW','statFormula'].forEach(id=>document.getElementById(id).textContent='—');
  document.getElementById('atomLegend').innerHTML='<div style="font-family:\'JetBrains Mono\',monospace;font-size:10px;color:var(--text-muted);">Load a molecule to see elements</div>';
  render();
  saveAppState();
}

// ═══════════════════════════════════════════════════════════
